name: "SCA with Snyk"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  snyk-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'      # Juice Shop OK avec 18/20. Garde 18 pour npm install stable.

    - name: Install dependencies
      run: npm install

    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/node@master
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --json-file-output=snyk-report.json

    - name: Upload Snyk JSON report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: snyk-security-report
        path: snyk-report.json